interestPoints = 
[
{
  "ID": "1",
  "description": "生科草坪",
  "longitude": 116.313664,
  "latitude": 39.99243,
  "imgp": "figure/taxa/1_L2_phylum.png",
  "imgc": "figure/taxa/1_L3_class.png",
  "imgo": "figure/taxa/1_L4_order.png",
  "imgf": "figure/taxa/1_L5_family.png",
  "imgg": "figure/taxa/1_L6_genus.png",
  "photo": "figure/photo/1.jpg"
},
{
  "ID": "10",
  "description": "三教",
  "longitude": 116.313518,
  "latitude": 39.9893,
  "imgp": "figure/taxa/10_L2_phylum.png",
  "imgc": "figure/taxa/10_L3_class.png",
  "imgo": "figure/taxa/10_L4_order.png",
  "imgf": "figure/taxa/10_L5_family.png",
  "imgg": "figure/taxa/10_L6_genus.png",
  "photo": "figure/photo/10.jpg"
},
{
  "ID": "11",
  "description": "燕园大厦",
  "longitude": 116.314498,
  "latitude": 39.98775,
  "imgp": "figure/taxa/11_L2_phylum.png",
  "imgc": "figure/taxa/11_L3_class.png",
  "imgo": "figure/taxa/11_L4_order.png",
  "imgf": "figure/taxa/11_L5_family.png",
  "imgg": "figure/taxa/11_L6_genus.png",
  "photo": "figure/photo/11.jpg"
},
{
  "ID": "12",
  "description": "邱德拔",
  "longitude": 116.314556,
  "latitude": 39.98891,
  "imgp": "figure/taxa/12_L2_phylum.png",
  "imgc": "figure/taxa/12_L3_class.png",
  "imgo": "figure/taxa/12_L4_order.png",
  "imgf": "figure/taxa/12_L5_family.png",
  "imgg": "figure/taxa/12_L6_genus.png",
  "photo": "figure/photo/12.jpg"
},
{
  "ID": "13",
  "description": "五四运动场",
  "longitude": 116.313498,
  "latitude": 39.98799,
  "imgp": "figure/taxa/13_L2_phylum.png",
  "imgc": "figure/taxa/13_L3_class.png",
  "imgo": "figure/taxa/13_L4_order.png",
  "imgf": "figure/taxa/13_L5_family.png",
  "imgg": "figure/taxa/13_L6_genus.png",
  "photo": "figure/photo/13.jpg"
},
{
  "ID": "14",
  "description": "对外汉语教育学院",
  "longitude": 116.311582,
  "latitude": 39.98797,
  "imgp": "figure/taxa/14_L2_phylum.png",
  "imgc": "figure/taxa/14_L3_class.png",
  "imgo": "figure/taxa/14_L4_order.png",
  "imgf": "figure/taxa/14_L5_family.png",
  "imgg": "figure/taxa/14_L6_genus.png",
  "photo": "figure/photo/14.jpg"
},
{
  "ID": "16",
  "description": "农园",
  "longitude": 116.312125,
  "latitude": 39.98933,
  "imgp": "figure/taxa/16_L2_phylum.png",
  "imgc": "figure/taxa/16_L3_class.png",
  "imgo": "figure/taxa/16_L4_order.png",
  "imgf": "figure/taxa/16_L5_family.png",
  "imgg": "figure/taxa/16_L6_genus.png",
  "photo": "figure/photo/16.jpg"
},
{
  "ID": "17",
  "description": "燕南园",
  "longitude": 116.310233,
  "latitude": 39.99068,
  "imgp": "figure/taxa/17_L2_phylum.png",
  "imgc": "figure/taxa/17_L3_class.png",
  "imgo": "figure/taxa/17_L4_order.png",
  "imgf": "figure/taxa/17_L5_family.png",
  "imgg": "figure/taxa/17_L6_genus.png",
  "photo": "figure/photo/17.jpg"
},
{
  "ID": "18",
  "description": "光华管理学院",
  "longitude": 116.311313,
  "latitude": 39.99054,
  "imgp": "figure/taxa/18_L2_phylum.png",
  "imgc": "figure/taxa/18_L3_class.png",
  "imgo": "figure/taxa/18_L4_order.png",
  "imgf": "figure/taxa/18_L5_family.png",
  "imgg": "figure/taxa/18_L6_genus.png",
  "photo": "figure/photo/18.jpg"
},
{
  "ID": "19",
  "description": "地学楼",
  "longitude": 116.311801,
  "latitude": 39.99194,
  "imgp": "figure/taxa/19_L2_phylum.png",
  "imgc": "figure/taxa/19_L3_class.png",
  "imgo": "figure/taxa/19_L4_order.png",
  "imgf": "figure/taxa/19_L5_family.png",
  "imgg": "figure/taxa/19_L6_genus.png",
  "photo": "figure/photo/19.jpg"
},
{
  "ID": "2",
  "description": "东侧门",
  "longitude": 116.315041,
  "latitude": 39.99293,
  "imgp": "figure/taxa/2_L2_phylum.png",
  "imgc": "figure/taxa/2_L3_class.png",
  "imgo": "figure/taxa/2_L4_order.png",
  "imgf": "figure/taxa/2_L5_family.png",
  "imgg": "figure/taxa/2_L6_genus.png",
  "photo": "figure/photo/2.jpg"
},
{
  "ID": "20",
  "description": "图书馆",
  "longitude": 116.310716,
  "latitude": 39.99188,
  "imgp": "figure/taxa/20_L2_phylum.png",
  "imgc": "figure/taxa/20_L3_class.png",
  "imgo": "figure/taxa/20_L4_order.png",
  "imgf": "figure/taxa/20_L5_family.png",
  "imgg": "figure/taxa/20_L6_genus.png",
  "photo": "figure/photo/20.jpg"
},
{
  "ID": "21-1",
  "description": "一教",
  "longitude": 116.310148,
  "latitude": 39.99256,
  "imgp": "figure/taxa/21-1_L2_phylum.png",
  "imgc": "figure/taxa/21-1_L3_class.png",
  "imgo": "figure/taxa/21-1_L4_order.png",
  "imgf": "figure/taxa/21-1_L5_family.png",
  "imgg": "figure/taxa/21-1_L6_genus.png",
  "photo": "figure/photo/45312.jpg"
},
{
  "ID": "21-2",
  "description": "百周年纪念讲堂",
  "longitude": 116.31058,
  "latitude": 39.9899,
  "imgp": "figure/taxa/21-2_L2_phylum.png",
  "imgc": "figure/taxa/21-2_L3_class.png",
  "imgo": "figure/taxa/21-2_L4_order.png",
  "imgf": "figure/taxa/21-2_L5_family.png",
  "imgg": "figure/taxa/21-2_L6_genus.png",
  "photo": "figure/photo/45343.jpg"
},
{
  "ID": "23-1",
  "description": "教育学院",
  "longitude": 116.311572,
  "latitude": 39.98891,
  "imgp": "figure/taxa/23-1_L2_phylum.png",
  "imgc": "figure/taxa/23-1_L3_class.png",
  "imgo": "figure/taxa/23-1_L4_order.png",
  "imgf": "figure/taxa/23-1_L5_family.png",
  "imgg": "figure/taxa/23-1_L6_genus.png",
  "photo": "figure/photo/45314.jpg"
},
{
  "ID": "23-2",
  "description": "38-39宿舍区",
  "longitude": 116.308488,
  "latitude": 39.98728,
  "imgp": "figure/taxa/23-2_L2_phylum.png",
  "imgc": "figure/taxa/23-2_L3_class.png",
  "imgo": "figure/taxa/23-2_L4_order.png",
  "imgf": "figure/taxa/23-2_L5_family.png",
  "imgg": "figure/taxa/23-2_L6_genus.png",
  "photo": "figure/photo/45345.jpg"
},
{
  "ID": "24",
  "description": "文明科学雕塑",
  "longitude": 116.309732,
  "latitude": 39.98827,
  "imgp": "figure/taxa/24_L2_phylum.png",
  "imgc": "figure/taxa/24_L3_class.png",
  "imgo": "figure/taxa/24_L4_order.png",
  "imgf": "figure/taxa/24_L5_family.png",
  "imgg": "figure/taxa/24_L6_genus.png",
  "photo": "figure/photo/24.jpg"
},
{
  "ID": "25",
  "description": "学一",
  "longitude": 116.307826,
  "latitude": 39.98734,
  "imgp": "figure/taxa/25_L2_phylum.png",
  "imgc": "figure/taxa/25_L3_class.png",
  "imgo": "figure/taxa/25_L4_order.png",
  "imgf": "figure/taxa/25_L5_family.png",
  "imgg": "figure/taxa/25_L6_genus.png",
  "photo": "figure/photo/25.jpg"
},
{
  "ID": "27",
  "description": "燕南园中间",
  "longitude": 116.309413,
  "latitude": 39.98967,
  "imgp": "figure/taxa/27_L2_phylum.png",
  "imgc": "figure/taxa/27_L3_class.png",
  "imgo": "figure/taxa/27_L4_order.png",
  "imgf": "figure/taxa/27_L5_family.png",
  "imgg": "figure/taxa/27_L6_genus.png",
  "photo": "figure/photo/27.jpg"
},
{
  "ID": "28",
  "description": "学五草坪",
  "longitude": 116.3073,
  "latitude": 39.98895,
  "imgp": "figure/taxa/28_L2_phylum.png",
  "imgc": "figure/taxa/28_L3_class.png",
  "imgo": "figure/taxa/28_L4_order.png",
  "imgf": "figure/taxa/28_L5_family.png",
  "imgg": "figure/taxa/28_L6_genus.png",
  "photo": "figure/photo/28.jpg"
},
{
  "ID": "3",
  "description": "东门侧边",
  "longitude": 116.315221,
  "latitude": 39.99188,
  "imgp": "figure/taxa/3_L2_phylum.png",
  "imgc": "figure/taxa/3_L3_class.png",
  "imgo": "figure/taxa/3_L4_order.png",
  "imgf": "figure/taxa/3_L5_family.png",
  "imgg": "figure/taxa/3_L6_genus.png",
  "photo": "figure/photo/3.jpg"
},
{
  "ID": "30",
  "description": "静园草坪",
  "longitude": 116.308293,
  "latitude": 39.99174,
  "imgp": "figure/taxa/30_L2_phylum.png",
  "imgc": "figure/taxa/30_L3_class.png",
  "imgo": "figure/taxa/30_L4_order.png",
  "imgf": "figure/taxa/30_L5_family.png",
  "imgg": "figure/taxa/30_L6_genus.png",
  "photo": "figure/photo/30.jpg"
},
{
  "ID": "34",
  "description": "勺园",
  "longitude": 116.306253,
  "latitude": 39.99172,
  "imgp": "figure/taxa/34_L2_phylum.png",
  "imgc": "figure/taxa/34_L3_class.png",
  "imgo": "figure/taxa/34_L4_order.png",
  "imgf": "figure/taxa/34_L5_family.png",
  "imgg": "figure/taxa/34_L6_genus.png",
  "photo": "figure/photo/34.jpg"
},
{
  "ID": "35",
  "description": "佟园",
  "longitude": 116.306919,
  "latitude": 39.99111,
  "imgp": "figure/taxa/35_L2_phylum.png",
  "imgc": "figure/taxa/35_L3_class.png",
  "imgo": "figure/taxa/35_L4_order.png",
  "imgf": "figure/taxa/35_L5_family.png",
  "imgg": "figure/taxa/35_L6_genus.png",
  "photo": "figure/photo/35.jpg"
},
{
  "ID": "37",
  "description": "燕南园北侧",
  "longitude": 116.309241,
  "latitude": 39.99021,
  "imgp": "figure/taxa/37_L2_phylum.png",
  "imgc": "figure/taxa/37_L3_class.png",
  "imgo": "figure/taxa/37_L4_order.png",
  "imgf": "figure/taxa/37_L5_family.png",
  "imgg": "figure/taxa/37_L6_genus.png",
  "photo": "figure/photo/37.jpg"
},
{
  "ID": "38",
  "description": "45甲乙",
  "longitude": 116.30636,
  "latitude": 39.98986,
  "imgp": "figure/taxa/38_L2_phylum.png",
  "imgc": "figure/taxa/38_L3_class.png",
  "imgo": "figure/taxa/38_L4_order.png",
  "imgf": "figure/taxa/38_L5_family.png",
  "imgg": "figure/taxa/38_L6_genus.png",
  "photo": "figure/photo/38.jpg"
},
{
  "ID": "39",
  "description": "46-47宿舍区",
  "longitude": 116.306118,
  "latitude": 39.98861,
  "imgp": "figure/taxa/39_L2_phylum.png",
  "imgc": "figure/taxa/39_L3_class.png",
  "imgo": "figure/taxa/39_L4_order.png",
  "imgf": "figure/taxa/39_L5_family.png",
  "imgg": "figure/taxa/39_L6_genus.png",
  "photo": "figure/photo/39.jpg"
},
{
  "ID": "4",
  "description": "理教后门",
  "longitude": 116.313616,
  "latitude": 39.99169,
  "imgp": "figure/taxa/4_L2_phylum.png",
  "imgc": "figure/taxa/4_L3_class.png",
  "imgo": "figure/taxa/4_L4_order.png",
  "imgf": "figure/taxa/4_L5_family.png",
  "imgg": "figure/taxa/4_L6_genus.png",
  "photo": "figure/photo/4.jpg"
},
{
  "ID": "40",
  "description": "艺园",
  "longitude": 116.313509,
  "latitude": 39.99086,
  "imgp": "figure/taxa/40_L2_phylum.png",
  "imgc": "figure/taxa/40_L3_class.png",
  "imgo": "figure/taxa/40_L4_order.png",
  "imgf": "figure/taxa/40_L5_family.png",
  "imgg": "figure/taxa/40_L6_genus.png",
  "photo": "figure/photo/40.jpg"
},
{
  "ID": "43",
  "description": "阿卜杜勒阿齐兹图书馆",
  "longitude": 116.309511,
  "latitude": 39.99269,
  "imgp": "figure/taxa/43_L2_phylum.png",
  "imgc": "figure/taxa/43_L3_class.png",
  "imgo": "figure/taxa/43_L4_order.png",
  "imgf": "figure/taxa/43_L5_family.png",
  "imgg": "figure/taxa/43_L6_genus.png",
  "photo": "figure/photo/43.jpg"
},
{
  "ID": "44",
  "description": "生物标本馆",
  "longitude": 116.311606,
  "latitude": 39.99282,
  "imgp": "figure/taxa/44_L2_phylum.png",
  "imgc": "figure/taxa/44_L3_class.png",
  "imgo": "figure/taxa/44_L4_order.png",
  "imgf": "figure/taxa/44_L5_family.png",
  "imgg": "figure/taxa/44_L6_genus.png",
  "photo": "figure/photo/44.jpg"
},
{
  "ID": "46",
  "description": "燕南园南侧",
  "longitude": 116.308421,
  "latitude": 39.98923,
  "imgp": "figure/taxa/46_L2_phylum.png",
  "imgc": "figure/taxa/46_L3_class.png",
  "imgo": "figure/taxa/46_L4_order.png",
  "imgf": "figure/taxa/46_L5_family.png",
  "imgg": "figure/taxa/46_L6_genus.png",
  "photo": "figure/photo/46.jpg"
},
{
  "ID": "6",
  "description": "英杰交流中心",
  "longitude": 116.313953,
  "latitude": 39.99052,
  "imgp": "figure/taxa/6_L2_phylum.png",
  "imgc": "figure/taxa/6_L3_class.png",
  "imgo": "figure/taxa/6_L4_order.png",
  "imgf": "figure/taxa/6_L5_family.png",
  "imgg": "figure/taxa/6_L6_genus.png",
  "photo": "figure/photo/6.jpg"
},
{
  "ID": "7",
  "description": "理科二号楼",
  "longitude": 116.314386,
  "latitude": 39.99089,
  "imgp": "figure/taxa/7_L2_phylum.png",
  "imgc": "figure/taxa/7_L3_class.png",
  "imgo": "figure/taxa/7_L4_order.png",
  "imgf": "figure/taxa/7_L5_family.png",
  "imgg": "figure/taxa/7_L6_genus.png",
  "photo": "figure/photo/7.jpg"
},
{
  "ID": "8",
  "description": "二教",
  "longitude": 116.312905,
  "latitude": 39.98972,
  "imgp": "figure/taxa/8_L2_phylum.png",
  "imgc": "figure/taxa/8_L3_class.png",
  "imgo": "figure/taxa/8_L4_order.png",
  "imgf": "figure/taxa/8_L5_family.png",
  "imgg": "figure/taxa/8_L6_genus.png",
  "photo": "figure/photo/8.jpg"
},
{
  "ID": "CY1",
  "description": "葛利普墓，西门附近墓碑",
  "longitude": 116.305332,
  "latitude": 39.993746,
  "imgp": "figure/taxa/CY1_L2_phylum.png",
  "imgc": "figure/taxa/CY1_L3_class.png",
  "imgo": "figure/taxa/CY1_L4_order.png",
  "imgf": "figure/taxa/CY1_L5_family.png",
  "imgg": "figure/taxa/CY1_L6_genus.png",
  "photo": "figure/photo/CY1.jpg"
},
{
  "ID": "CY15",
  "description": "元培学院附近李大钊像",
  "longitude": 116.30817,
  "latitude": 39.992896,
  "imgp": "figure/taxa/CY15_L2_phylum.png",
  "imgc": "figure/taxa/CY15_L3_class.png",
  "imgo": "figure/taxa/CY15_L4_order.png",
  "imgf": "figure/taxa/CY15_L5_family.png",
  "imgg": "figure/taxa/CY15_L6_genus.png",
  "photo": "figure/photo/CY15.jpg"
},
{
  "ID": "CY16",
  "description": "办公楼附近蔡元培像",
  "longitude": 116.307366,
  "latitude": 39.994335,
  "imgp": "figure/taxa/CY16_L2_phylum.png",
  "imgc": "figure/taxa/CY16_L3_class.png",
  "imgo": "figure/taxa/CY16_L4_order.png",
  "imgf": "figure/taxa/CY16_L5_family.png",
  "imgg": "figure/taxa/CY16_L6_genus.png",
  "photo": "figure/photo/CY16.jpg"
},
{
  "ID": "CY17",
  "description": "未名湖西岸石碑",
  "longitude": 116.308011,
  "latitude": 39.994562,
  "imgp": "figure/taxa/CY17_L2_phylum.png",
  "imgc": "figure/taxa/CY17_L3_class.png",
  "imgo": "figure/taxa/CY17_L4_order.png",
  "imgf": "figure/taxa/CY17_L5_family.png",
  "imgg": "figure/taxa/CY17_L6_genus.png",
  "photo": "figure/photo/CY17.jpg"
},
{
  "ID": "CY18",
  "description": "未名湖南石墩，花神庙",
  "longitude": 116.309982,
  "latitude": 39.994087,
  "imgp": "figure/taxa/CY18_L2_phylum.png",
  "imgc": "figure/taxa/CY18_L3_class.png",
  "imgo": "figure/taxa/CY18_L4_order.png",
  "imgf": "figure/taxa/CY18_L5_family.png",
  "imgg": "figure/taxa/CY18_L6_genus.png",
  "photo": "figure/photo/CY18.jpg"
},
{
  "ID": "CY19",
  "description": "博雅塔下石碑",
  "longitude": 116.311841,
  "latitude": 39.993963,
  "imgp": "figure/taxa/CY19_L2_phylum.png",
  "imgc": "figure/taxa/CY19_L3_class.png",
  "imgo": "figure/taxa/CY19_L4_order.png",
  "imgf": "figure/taxa/CY19_L5_family.png",
  "imgg": "figure/taxa/CY19_L6_genus.png",
  "photo": "figure/photo/CY19.jpg"
},
{
  "ID": "CY2",
  "description": "西南联大纪念碑，西门附近石碑",
  "longitude": 116.305272,
  "latitude": 39.99372,
  "imgp": "figure/taxa/CY2_L2_phylum.png",
  "imgc": "figure/taxa/CY2_L3_class.png",
  "imgo": "figure/taxa/CY2_L4_order.png",
  "imgf": "figure/taxa/CY2_L5_family.png",
  "imgg": "figure/taxa/CY2_L6_genus.png",
  "photo": "figure/photo/CY2.jpg"
},
{
  "ID": "CY3",
  "description": "校史馆馆前台阶",
  "longitude": 116.306078,
  "latitude": 39.993284,
  "imgp": "figure/taxa/CY3_L2_phylum.png",
  "imgc": "figure/taxa/CY3_L3_class.png",
  "imgo": "figure/taxa/CY3_L4_order.png",
  "imgf": "figure/taxa/CY3_L5_family.png",
  "imgg": "figure/taxa/CY3_L6_genus.png",
  "photo": "figure/photo/CY3.jpg"
},
{
  "ID": "CY35",
  "description": "西门校友桥桥梁栏杆",
  "longitude": 116.30506,
  "latitude": 39.994592,
  "imgp": "figure/taxa/CY35_L2_phylum.png",
  "imgc": "figure/taxa/CY35_L3_class.png",
  "imgo": "figure/taxa/CY35_L4_order.png",
  "imgf": "figure/taxa/CY35_L5_family.png",
  "imgg": "figure/taxa/CY35_L6_genus.png",
  "photo": "figure/photo/CY35.jpg"
},
{
  "ID": "CY36",
  "description": "西门华表栏杆",
  "longitude": 116.305477,
  "latitude": 39.994523,
  "imgp": "figure/taxa/CY36_L2_phylum.png",
  "imgc": "figure/taxa/CY36_L3_class.png",
  "imgo": "figure/taxa/CY36_L4_order.png",
  "imgf": "figure/taxa/CY36_L5_family.png",
  "imgg": "figure/taxa/CY36_L6_genus.png",
  "photo": "figure/photo/CY36.jpg"
},
{
  "ID": "CY4",
  "description": "塞万提斯像",
  "longitude": 116.305998,
  "latitude": 39.992798,
  "imgp": "figure/taxa/CY4_L2_phylum.png",
  "imgc": "figure/taxa/CY4_L3_class.png",
  "imgo": "figure/taxa/CY4_L4_order.png",
  "imgf": "figure/taxa/CY4_L5_family.png",
  "imgg": "figure/taxa/CY4_L6_genus.png",
  "photo": "figure/photo/CY4.jpg"
},
{
  "ID": "CY40",
  "description": "李兆基人文学苑石刻",
  "longitude": 116.311648,
  "latitude": 39.996653,
  "imgp": "figure/taxa/CY40_L2_phylum.png",
  "imgc": "figure/taxa/CY40_L3_class.png",
  "imgo": "figure/taxa/CY40_L4_order.png",
  "imgf": "figure/taxa/CY40_L5_family.png",
  "imgg": "figure/taxa/CY40_L6_genus.png",
  "photo": "figure/photo/CY40.jpg"
},
{
  "ID": "CY41",
  "description": "科维理研究所我ai北大天文",
  "longitude": 116.310766,
  "latitude": 39.999196,
  "imgp": "figure/taxa/CY41_L2_phylum.png",
  "imgc": "figure/taxa/CY41_L3_class.png",
  "imgo": "figure/taxa/CY41_L4_order.png",
  "imgf": "figure/taxa/CY41_L5_family.png",
  "imgg": "figure/taxa/CY41_L6_genus.png",
  "photo": "figure/photo/CY41.jpg"
},
{
  "ID": "CY48",
  "description": "经济学院综合楼石刻",
  "longitude": 116.312876,
  "latitude": 39.996839,
  "imgp": "figure/taxa/CY48_L2_phylum.png",
  "imgc": "figure/taxa/CY48_L3_class.png",
  "imgo": "figure/taxa/CY48_L4_order.png",
  "imgf": "figure/taxa/CY48_L5_family.png",
  "imgg": "figure/taxa/CY48_L6_genus.png",
  "photo": "figure/photo/CY48.jpg"
},
{
  "ID": "CY49",
  "description": "教育基金会石狮",
  "longitude": 116.310393,
  "latitude": 39.996922,
  "imgp": "figure/taxa/CY49_L2_phylum.png",
  "imgc": "figure/taxa/CY49_L3_class.png",
  "imgo": "figure/taxa/CY49_L4_order.png",
  "imgf": "figure/taxa/CY49_L5_family.png",
  "imgg": "figure/taxa/CY49_L6_genus.png",
  "photo": "figure/photo/CY49.jpg"
},
{
  "ID": "CY50",
  "description": "郎润园无名桥桥梁栏杆",
  "longitude": 116.310716,
  "latitude": 39.997667,
  "imgp": "figure/taxa/CY50_L2_phylum.png",
  "imgc": "figure/taxa/CY50_L3_class.png",
  "imgo": "figure/taxa/CY50_L4_order.png",
  "imgf": "figure/taxa/CY50_L5_family.png",
  "imgg": "figure/taxa/CY50_L6_genus.png",
  "photo": "figure/photo/CY50.jpg"
},
{
  "ID": "CY51",
  "description": "房地产管理部消防器材存放柜",
  "longitude": 116.306859,
  "latitude": 39.987361,
  "imgp": "figure/taxa/CY51_L2_phylum.png",
  "imgc": "figure/taxa/CY51_L3_class.png",
  "imgo": "figure/taxa/CY51_L4_order.png",
  "imgf": "figure/taxa/CY51_L5_family.png",
  "imgg": "figure/taxa/CY51_L6_genus.png",
  "photo": "figure/photo/CY51.jpg"
},
{
  "ID": "FXY-1",
  "description": "北京市海淀区·北京大学",
  "longitude": 116.313009,
  "latitude": 39.994612,
  "imgp": "figure/taxa/FXY-1_L2_phylum.png",
  "imgc": "figure/taxa/FXY-1_L3_class.png",
  "imgo": "figure/taxa/FXY-1_L4_order.png",
  "imgf": "figure/taxa/FXY-1_L5_family.png",
  "imgg": "figure/taxa/FXY-1_L6_genus.png",
  "photo": "figure/photo/FXY-1.jpg"
},
{
  "ID": "FXY-2",
  "description": "北京市海淀区·北京大学",
  "longitude": 116.313129,
  "latitude": 39.993837,
  "imgp": "figure/taxa/FXY-2_L2_phylum.png",
  "imgc": "figure/taxa/FXY-2_L3_class.png",
  "imgo": "figure/taxa/FXY-2_L4_order.png",
  "imgf": "figure/taxa/FXY-2_L5_family.png",
  "imgg": "figure/taxa/FXY-2_L6_genus.png",
  "photo": "figure/photo/FXY-2.jpg"
},
{
  "ID": "JMq-1",
  "description": "北京市海淀区·北京大学",
  "longitude": 116.311807,
  "latitude": 39.998046,
  "imgp": "figure/taxa/JMq-1_L2_phylum.png",
  "imgc": "figure/taxa/JMq-1_L3_class.png",
  "imgo": "figure/taxa/JMq-1_L4_order.png",
  "imgf": "figure/taxa/JMq-1_L5_family.png",
  "imgg": "figure/taxa/JMq-1_L6_genus.png",
  "photo": "figure/photo/JMq-1.jpg"
},
{
  "ID": "JMq-2",
  "description": "北京市海淀区·北京大学历史学系",
  "longitude": 116.311029,
  "latitude": 39.997525,
  "imgp": "figure/taxa/JMq-2_L2_phylum.png",
  "imgc": "figure/taxa/JMq-2_L3_class.png",
  "imgo": "figure/taxa/JMq-2_L4_order.png",
  "imgf": "figure/taxa/JMq-2_L5_family.png",
  "imgg": "figure/taxa/JMq-2_L6_genus.png",
  "photo": "figure/photo/JMq-2.jpg"
},
{
  "ID": "JMq-3",
  "description": "北京市海淀区·北京大学历史学系",
  "longitude": 116.310696,
  "latitude": 39.997083,
  "imgp": "figure/taxa/JMq-3_L2_phylum.png",
  "imgc": "figure/taxa/JMq-3_L3_class.png",
  "imgo": "figure/taxa/JMq-3_L4_order.png",
  "imgf": "figure/taxa/JMq-3_L5_family.png",
  "imgg": "figure/taxa/JMq-3_L6_genus.png",
  "photo": "figure/photo/JMq-3.jpg"
},
{
  "ID": "JMq-4",
  "description": "北京市海淀区·北京大学",
  "longitude": 116.310778,
  "latitude": 39.996581,
  "imgp": "figure/taxa/JMq-4_L2_phylum.png",
  "imgc": "figure/taxa/JMq-4_L3_class.png",
  "imgo": "figure/taxa/JMq-4_L4_order.png",
  "imgf": "figure/taxa/JMq-4_L5_family.png",
  "imgg": "figure/taxa/JMq-4_L6_genus.png",
  "photo": "figure/photo/JMq-4.jpg"
},
{
  "ID": "JMQS-1",
  "description": "北京市海淀区·北京大学",
  "longitude": 116.311299,
  "latitude": 39.998395,
  "imgp": "figure/taxa/JMQS-1_L2_phylum.png",
  "imgc": "figure/taxa/JMQS-1_L3_class.png",
  "imgo": "figure/taxa/JMQS-1_L4_order.png",
  "imgf": "figure/taxa/JMQS-1_L5_family.png",
  "imgg": "figure/taxa/JMQS-1_L6_genus.png",
  "photo": "figure/photo/JMQS-1.jpg"
},
{
  "ID": "JMQS-2",
  "description": "北京市海淀区·北京大学",
  "longitude": 116.310957,
  "latitude": 39.996462,
  "imgp": "figure/taxa/JMQS-2_L2_phylum.png",
  "imgc": "figure/taxa/JMQS-2_L3_class.png",
  "imgo": "figure/taxa/JMQS-2_L4_order.png",
  "imgf": "figure/taxa/JMQS-2_L5_family.png",
  "imgg": "figure/taxa/JMQS-2_L6_genus.png",
  "photo": "figure/photo/JMQS-2.jpg"
},
{
  "ID": "S-1",
  "description": "北京市海淀区·北京大学",
  "longitude": 116.30676,
  "latitude": 39.996433,
  "imgp": "figure/taxa/S-1_L2_phylum.png",
  "imgc": "figure/taxa/S-1_L3_class.png",
  "imgo": "figure/taxa/S-1_L4_order.png",
  "imgf": "figure/taxa/S-1_L5_family.png",
  "imgg": "figure/taxa/S-1_L6_genus.png",
  "photo": "figure/photo/S-1.jpg"
},
{
  "ID": "S-2",
  "description": "北京市海淀区·北京大学生物技术楼",
  "longitude": 116.305524,
  "latitude": 39.99653,
  "imgp": "figure/taxa/S-2_L2_phylum.png",
  "imgc": "figure/taxa/S-2_L3_class.png",
  "imgo": "figure/taxa/S-2_L4_order.png",
  "imgf": "figure/taxa/S-2_L5_family.png",
  "imgg": "figure/taxa/S-2_L6_genus.png",
  "photo": "figure/photo/S-2.jpg"
},
{
  "ID": "WMH-1",
  "description": "北京市海淀区·北京大学",
  "longitude": 116.310451,
  "latitude": 39.993959,
  "imgp": "figure/taxa/WMH-1_L2_phylum.png",
  "imgc": "figure/taxa/WMH-1_L3_class.png",
  "imgo": "figure/taxa/WMH-1_L4_order.png",
  "imgf": "figure/taxa/WMH-1_L5_family.png",
  "imgg": "figure/taxa/WMH-1_L6_genus.png",
  "photo": "figure/photo/WMH-1.jpg"
},
{
  "ID": "WMH-10",
  "description": "北京市海淀区·北京大学",
  "longitude": 116.308101,
  "latitude": 39.994956,
  "imgp": "figure/taxa/WMH-10_L2_phylum.png",
  "imgc": "figure/taxa/WMH-10_L3_class.png",
  "imgo": "figure/taxa/WMH-10_L4_order.png",
  "imgf": "figure/taxa/WMH-10_L5_family.png",
  "imgg": "figure/taxa/WMH-10_L6_genus.png",
  "photo": "figure/photo/WMH-10.jpg"
},
{
  "ID": "WMH-11",
  "description": "北京市海淀区·北京大学",
  "longitude": 116.307549,
  "latitude": 39.995098,
  "imgp": "figure/taxa/WMH-11_L2_phylum.png",
  "imgc": "figure/taxa/WMH-11_L3_class.png",
  "imgo": "figure/taxa/WMH-11_L4_order.png",
  "imgf": "figure/taxa/WMH-11_L5_family.png",
  "imgg": "figure/taxa/WMH-11_L6_genus.png",
  "photo": "figure/photo/WMH-11.jpg"
},
{
  "ID": "WMH-12",
  "description": "北京市海淀区·北京大学办公楼",
  "longitude": 116.306686,
  "latitude": 39.994983,
  "imgp": "figure/taxa/WMH-12_L2_phylum.png",
  "imgc": "figure/taxa/WMH-12_L3_class.png",
  "imgo": "figure/taxa/WMH-12_L4_order.png",
  "imgf": "figure/taxa/WMH-12_L5_family.png",
  "imgg": "figure/taxa/WMH-12_L6_genus.png",
  "photo": "figure/photo/WMH-12.jpg"
},
{
  "ID": "WMH-13",
  "description": "北京市海淀区·北京大学办公楼",
  "longitude": 116.306348,
  "latitude": 39.995477,
  "imgp": "figure/taxa/WMH-13_L2_phylum.png",
  "imgc": "figure/taxa/WMH-13_L3_class.png",
  "imgo": "figure/taxa/WMH-13_L4_order.png",
  "imgf": "figure/taxa/WMH-13_L5_family.png",
  "imgg": "figure/taxa/WMH-13_L6_genus.png",
  "photo": "figure/photo/WMH-13.jpg"
},
{
  "ID": "WMH-14",
  "description": "北京市海淀区·北京大学",
  "longitude": 116.306548,
  "latitude": 39.995942,
  "imgp": "figure/taxa/WMH-14_L2_phylum.png",
  "imgc": "figure/taxa/WMH-14_L3_class.png",
  "imgo": "figure/taxa/WMH-14_L4_order.png",
  "imgf": "figure/taxa/WMH-14_L5_family.png",
  "imgg": "figure/taxa/WMH-14_L6_genus.png",
  "photo": "figure/photo/WMH-14.jpg"
},
{
  "ID": "WMH-15",
  "description": "北京市海淀区·北京大学",
  "longitude": 116.306892,
  "latitude": 39.996272,
  "imgp": "figure/taxa/WMH-15_L2_phylum.png",
  "imgc": "figure/taxa/WMH-15_L3_class.png",
  "imgo": "figure/taxa/WMH-15_L4_order.png",
  "imgf": "figure/taxa/WMH-15_L5_family.png",
  "imgg": "figure/taxa/WMH-15_L6_genus.png",
  "photo": "figure/photo/WMH-15.jpg"
},
{
  "ID": "WMH-16",
  "description": "北京市海淀区·北京大学",
  "longitude": 116.307183,
  "latitude": 39.996471,
  "imgp": "figure/taxa/WMH-16_L2_phylum.png",
  "imgc": "figure/taxa/WMH-16_L3_class.png",
  "imgo": "figure/taxa/WMH-16_L4_order.png",
  "imgf": "figure/taxa/WMH-16_L5_family.png",
  "imgg": "figure/taxa/WMH-16_L6_genus.png",
  "photo": "figure/photo/WMH-16.jpg"
},
{
  "ID": "WMH-17",
  "description": "北京市海淀区·北京大学生物技术楼",
  "longitude": 116.305975,
  "latitude": 39.996165,
  "imgp": "figure/taxa/WMH-17_L2_phylum.png",
  "imgc": "figure/taxa/WMH-17_L3_class.png",
  "imgo": "figure/taxa/WMH-17_L4_order.png",
  "imgf": "figure/taxa/WMH-17_L5_family.png",
  "imgg": "figure/taxa/WMH-17_L6_genus.png",
  "photo": "figure/photo/WMH-17.jpg"
},
{
  "ID": "WMH-18",
  "description": "北京市海淀区·北京大学生物技术楼",
  "longitude": 116.305412,
  "latitude": 39.996475,
  "imgp": "figure/taxa/WMH-18_L2_phylum.png",
  "imgc": "figure/taxa/WMH-18_L3_class.png",
  "imgo": "figure/taxa/WMH-18_L4_order.png",
  "imgf": "figure/taxa/WMH-18_L5_family.png",
  "imgg": "figure/taxa/WMH-18_L6_genus.png",
  "photo": "figure/photo/WMH-18.jpg"
},
{
  "ID": "WMH-19",
  "description": "北京市海淀区·北京大学生物技术楼",
  "longitude": 116.305125,
  "latitude": 39.995732,
  "imgp": "figure/taxa/WMH-19_L2_phylum.png",
  "imgc": "figure/taxa/WMH-19_L3_class.png",
  "imgo": "figure/taxa/WMH-19_L4_order.png",
  "imgf": "figure/taxa/WMH-19_L5_family.png",
  "imgg": "figure/taxa/WMH-19_L6_genus.png",
  "photo": "figure/photo/WMH-19.jpg"
},
{
  "ID": "WMH-2",
  "description": "北京市海淀区·北京大学",
  "longitude": 116.31141,
  "latitude": 39.993931,
  "imgp": "figure/taxa/WMH-2_L2_phylum.png",
  "imgc": "figure/taxa/WMH-2_L3_class.png",
  "imgo": "figure/taxa/WMH-2_L4_order.png",
  "imgf": "figure/taxa/WMH-2_L5_family.png",
  "imgg": "figure/taxa/WMH-2_L6_genus.png",
  "photo": "figure/photo/WMH-2.jpg"
},
{
  "ID": "WMH-20",
  "description": "北京市海淀区·北京大学",
  "longitude": 116.304669,
  "latitude": 39.995614,
  "imgp": "figure/taxa/WMH-20_L2_phylum.png",
  "imgc": "figure/taxa/WMH-20_L3_class.png",
  "imgo": "figure/taxa/WMH-20_L4_order.png",
  "imgf": "figure/taxa/WMH-20_L5_family.png",
  "imgg": "figure/taxa/WMH-20_L6_genus.png",
  "photo": "figure/photo/WMH-20.jpg"
},
{
  "ID": "WMH-21",
  "description": "北京市海淀区·北京大学",
  "longitude": 116.304789,
  "latitude": 39.994884,
  "imgp": "figure/taxa/WMH-21_L2_phylum.png",
  "imgc": "figure/taxa/WMH-21_L3_class.png",
  "imgo": "figure/taxa/WMH-21_L4_order.png",
  "imgf": "figure/taxa/WMH-21_L5_family.png",
  "imgg": "figure/taxa/WMH-21_L6_genus.png",
  "photo": "figure/photo/WMH-21.jpg"
},
{
  "ID": "WMH-22",
  "description": "北京市海淀区·北京大学",
  "longitude": 116.305126,
  "latitude": 39.993661,
  "imgp": "figure/taxa/WMH-22_L2_phylum.png",
  "imgc": "figure/taxa/WMH-22_L3_class.png",
  "imgo": "figure/taxa/WMH-22_L4_order.png",
  "imgf": "figure/taxa/WMH-22_L5_family.png",
  "imgg": "figure/taxa/WMH-22_L6_genus.png",
  "photo": "figure/photo/WMH-22.jpg"
},
{
  "ID": "WMH-23",
  "description": "北京市海淀区·北京大学",
  "longitude": 116.305676,
  "latitude": 39.993254,
  "imgp": "figure/taxa/WMH-23_L2_phylum.png",
  "imgc": "figure/taxa/WMH-23_L3_class.png",
  "imgo": "figure/taxa/WMH-23_L4_order.png",
  "imgf": "figure/taxa/WMH-23_L5_family.png",
  "imgg": "figure/taxa/WMH-23_L6_genus.png",
  "photo": "figure/photo/WMH-23.jpg"
},
{
  "ID": "WMH-24",
  "description": "北京市海淀区·北京大学",
  "longitude": 116.307848,
  "latitude": 39.992863,
  "imgp": "figure/taxa/WMH-24_L2_phylum.png",
  "imgc": "figure/taxa/WMH-24_L3_class.png",
  "imgo": "figure/taxa/WMH-24_L4_order.png",
  "imgf": "figure/taxa/WMH-24_L5_family.png",
  "imgg": "figure/taxa/WMH-24_L6_genus.png",
  "photo": "figure/photo/WMH-24.jpg"
},
{
  "ID": "WMH-25",
  "description": "北京市海淀区·北京大学",
  "longitude": 116.308123,
  "latitude": 39.992035,
  "imgp": "figure/taxa/WMH-25_L2_phylum.png",
  "imgc": "figure/taxa/WMH-25_L3_class.png",
  "imgo": "figure/taxa/WMH-25_L4_order.png",
  "imgf": "figure/taxa/WMH-25_L5_family.png",
  "imgg": "figure/taxa/WMH-25_L6_genus.png",
  "photo": "figure/photo/WMH-25.jpg"
},
{
  "ID": "WMH-3",
  "description": "北京市海淀区·北京大学",
  "longitude": 116.310878,
  "latitude": 39.995696,
  "imgp": "figure/taxa/WMH-3_L2_phylum.png",
  "imgc": "figure/taxa/WMH-3_L3_class.png",
  "imgo": "figure/taxa/WMH-3_L4_order.png",
  "imgf": "figure/taxa/WMH-3_L5_family.png",
  "imgg": "figure/taxa/WMH-3_L6_genus.png",
  "photo": "figure/photo/WMH-3.jpg"
},
{
  "ID": "WMH-4",
  "description": "北京市海淀区·北京大学",
  "longitude": 116.310039,
  "latitude": 39.995626,
  "imgp": "figure/taxa/WMH-4_L2_phylum.png",
  "imgc": "figure/taxa/WMH-4_L3_class.png",
  "imgo": "figure/taxa/WMH-4_L4_order.png",
  "imgf": "figure/taxa/WMH-4_L5_family.png",
  "imgg": "figure/taxa/WMH-4_L6_genus.png",
  "photo": "figure/photo/WMH-4.jpg"
},
{
  "ID": "WMH-5",
  "description": "北京市海淀区·北京大学",
  "longitude": 116.309162,
  "latitude": 39.995369,
  "imgp": "figure/taxa/WMH-5_L2_phylum.png",
  "imgc": "figure/taxa/WMH-5_L3_class.png",
  "imgo": "figure/taxa/WMH-5_L4_order.png",
  "imgf": "figure/taxa/WMH-5_L5_family.png",
  "imgg": "figure/taxa/WMH-5_L6_genus.png",
  "photo": "figure/photo/WMH-5.jpg"
},
{
  "ID": "WMH-6",
  "description": "北京市海淀区·北京大学",
  "longitude": 116.309206,
  "latitude": 39.994788,
  "imgp": "figure/taxa/WMH-6_L2_phylum.png",
  "imgc": "figure/taxa/WMH-6_L3_class.png",
  "imgo": "figure/taxa/WMH-6_L4_order.png",
  "imgf": "figure/taxa/WMH-6_L5_family.png",
  "imgg": "figure/taxa/WMH-6_L6_genus.png",
  "photo": "figure/photo/WMH-6.jpg"
},
{
  "ID": "WMH-7",
  "description": "北京市海淀区·北京大学",
  "longitude": 116.308984,
  "latitude": 39.994692,
  "imgp": "figure/taxa/WMH-7_L2_phylum.png",
  "imgc": "figure/taxa/WMH-7_L3_class.png",
  "imgo": "figure/taxa/WMH-7_L4_order.png",
  "imgf": "figure/taxa/WMH-7_L5_family.png",
  "imgg": "figure/taxa/WMH-7_L6_genus.png",
  "photo": "figure/photo/WMH-7.jpg"
},
{
  "ID": "WMH-8",
  "description": "北京市海淀区·北京大学",
  "longitude": 116.308876,
  "latitude": 39.994709,
  "imgp": "figure/taxa/WMH-8_L2_phylum.png",
  "imgc": "figure/taxa/WMH-8_L3_class.png",
  "imgo": "figure/taxa/WMH-8_L4_order.png",
  "imgf": "figure/taxa/WMH-8_L5_family.png",
  "imgg": "figure/taxa/WMH-8_L6_genus.png",
  "photo": "figure/photo/WMH-8.jpg"
},
{
  "ID": "WMH-9",
  "description": "北京市海淀区·北京大学",
  "longitude": 116.308825,
  "latitude": 39.995195,
  "imgp": "figure/taxa/WMH-9_L2_phylum.png",
  "imgc": "figure/taxa/WMH-9_L3_class.png",
  "imgo": "figure/taxa/WMH-9_L4_order.png",
  "imgf": "figure/taxa/WMH-9_L5_family.png",
  "imgg": "figure/taxa/WMH-9_L6_genus.png",
  "photo": "figure/photo/WMH-9.jpg"
},
{
  "ID": "WMHS-1",
  "description": "北京市海淀区·北京大学",
  "longitude": 116.310329,
  "latitude": 39.994205,
  "imgp": "figure/taxa/WMHS-1_L2_phylum.png",
  "imgc": "figure/taxa/WMHS-1_L3_class.png",
  "imgo": "figure/taxa/WMHS-1_L4_order.png",
  "imgf": "figure/taxa/WMHS-1_L5_family.png",
  "imgg": "figure/taxa/WMHS-1_L6_genus.png",
  "photo": "figure/photo/WMHS-1.jpg"
},
{
  "ID": "WMHS-2",
  "description": "北京市海淀区·北京大学",
  "longitude": 116.310188,
  "latitude": 39.995534,
  "imgp": "figure/taxa/WMHS-2_L2_phylum.png",
  "imgc": "figure/taxa/WMHS-2_L3_class.png",
  "imgo": "figure/taxa/WMHS-2_L4_order.png",
  "imgf": "figure/taxa/WMHS-2_L5_family.png",
  "imgg": "figure/taxa/WMHS-2_L6_genus.png",
  "photo": "figure/photo/WMHS-2.jpg"
},
{
  "ID": "WSQ20",
  "description": "遥感楼门牌",
  "longitude": 116.312674,
  "latitude": 39.993197,
  "imgp": "figure/taxa/WSQ20_L2_phylum.png",
  "imgc": "figure/taxa/WSQ20_L3_class.png",
  "imgo": "figure/taxa/WSQ20_L4_order.png",
  "imgf": "figure/taxa/WSQ20_L5_family.png",
  "imgg": "figure/taxa/WSQ20_L6_genus.png",
  "photo": "figure/photo/WSQ20.jpg"
},
{
  "ID": "WSQ21",
  "description": "吕志和楼瑞幸咖啡窗户",
  "longitude": 116.313178,
  "latitude": 39.992291,
  "imgp": "figure/taxa/WSQ21_L2_phylum.png",
  "imgc": "figure/taxa/WSQ21_L3_class.png",
  "imgo": "figure/taxa/WSQ21_L4_order.png",
  "imgf": "figure/taxa/WSQ21_L5_family.png",
  "imgg": "figure/taxa/WSQ21_L6_genus.png",
  "photo": "figure/photo/WSQ21.jpg"
},
{
  "ID": "WSQ22",
  "description": "地学楼教室讲台",
  "longitude": 116.311874,
  "latitude": 39.991727,
  "imgp": "figure/taxa/WSQ22_L2_phylum.png",
  "imgc": "figure/taxa/WSQ22_L3_class.png",
  "imgo": "figure/taxa/WSQ22_L4_order.png",
  "imgf": "figure/taxa/WSQ22_L5_family.png",
  "imgg": "figure/taxa/WSQ22_L6_genus.png",
  "photo": "figure/photo/WSQ22.jpg"
},
{
  "ID": "WSQ23",
  "description": "光华管理学院1号楼寄存柜按钮",
  "longitude": 116.312224,
  "latitude": 39.990713,
  "imgp": "figure/taxa/WSQ23_L2_phylum.png",
  "imgc": "figure/taxa/WSQ23_L3_class.png",
  "imgo": "figure/taxa/WSQ23_L4_order.png",
  "imgf": "figure/taxa/WSQ23_L5_family.png",
  "imgg": "figure/taxa/WSQ23_L6_genus.png",
  "photo": "figure/photo/WSQ23.jpg"
},
{
  "ID": "WSQ24",
  "description": "理科教学楼（黄廷方楼）一楼圆凳",
  "longitude": 116.312943,
  "latitude": 39.991456,
  "imgp": "figure/taxa/WSQ24_L2_phylum.png",
  "imgc": "figure/taxa/WSQ24_L3_class.png",
  "imgo": "figure/taxa/WSQ24_L4_order.png",
  "imgf": "figure/taxa/WSQ24_L5_family.png",
  "imgg": "figure/taxa/WSQ24_L6_genus.png",
  "photo": "figure/photo/WSQ24.jpg"
},
{
  "ID": "WSQ25",
  "description": "第二教学楼自助售货机把手",
  "longitude": 116.313147,
  "latitude": 39.989452,
  "imgp": "figure/taxa/WSQ25_L2_phylum.png",
  "imgc": "figure/taxa/WSQ25_L3_class.png",
  "imgo": "figure/taxa/WSQ25_L4_order.png",
  "imgf": "figure/taxa/WSQ25_L5_family.png",
  "imgg": "figure/taxa/WSQ25_L6_genus.png",
  "photo": "figure/photo/WSQ25.jpg"
},
{
  "ID": "WSQ27",
  "description": "邱德拔体育馆西门柱子",
  "longitude": 116.315103,
  "latitude": 39.988655,
  "imgp": "figure/taxa/WSQ27_L2_phylum.png",
  "imgc": "figure/taxa/WSQ27_L3_class.png",
  "imgo": "figure/taxa/WSQ27_L4_order.png",
  "imgf": "figure/taxa/WSQ27_L5_family.png",
  "imgg": "figure/taxa/WSQ27_L6_genus.png",
  "photo": "figure/photo/WSQ27.jpg"
},
{
  "ID": "WSQ28",
  "description": "英杰交流中心玻璃门",
  "longitude": 116.313876,
  "latitude": 39.990738,
  "imgp": "figure/taxa/WSQ28_L2_phylum.png",
  "imgc": "figure/taxa/WSQ28_L3_class.png",
  "imgo": "figure/taxa/WSQ28_L4_order.png",
  "imgf": "figure/taxa/WSQ28_L5_family.png",
  "imgg": "figure/taxa/WSQ28_L6_genus.png",
  "photo": "figure/photo/WSQ28.jpg"
},
{
  "ID": "WSQ29",
  "description": "理科三号楼东门重点实验室牌子",
  "longitude": 116.314545,
  "latitude": 39.991664,
  "imgp": "figure/taxa/WSQ29_L2_phylum.png",
  "imgc": "figure/taxa/WSQ29_L3_class.png",
  "imgo": "figure/taxa/WSQ29_L4_order.png",
  "imgf": "figure/taxa/WSQ29_L5_family.png",
  "imgg": "figure/taxa/WSQ29_L6_genus.png",
  "photo": "figure/photo/WSQ29.jpg"
},
{
  "ID": "WSQ30",
  "description": "金光生命科学大楼南门柱子",
  "longitude": 116.314486,
  "latitude": 39.992452,
  "imgp": "figure/taxa/WSQ30_L2_phylum.png",
  "imgc": "figure/taxa/WSQ30_L3_class.png",
  "imgo": "figure/taxa/WSQ30_L4_order.png",
  "imgf": "figure/taxa/WSQ30_L5_family.png",
  "imgg": "figure/taxa/WSQ30_L6_genus.png",
  "photo": "figure/photo/WSQ30.jpg"
},
{
  "ID": "WSQ31",
  "description": "环境科学与工程学院室外圆桌",
  "longitude": 116.314722,
  "latitude": 39.994581,
  "imgp": "figure/taxa/WSQ31_L2_phylum.png",
  "imgc": "figure/taxa/WSQ31_L3_class.png",
  "imgo": "figure/taxa/WSQ31_L4_order.png",
  "imgf": "figure/taxa/WSQ31_L5_family.png",
  "imgg": "figure/taxa/WSQ31_L6_genus.png",
  "photo": "figure/photo/WSQ31.jpg"
},
{
  "ID": "WSQ32",
  "description": "法学院I love law 立牌",
  "longitude": 116.313506,
  "latitude": 39.994473,
  "imgp": "figure/taxa/WSQ32_L2_phylum.png",
  "imgc": "figure/taxa/WSQ32_L3_class.png",
  "imgo": "figure/taxa/WSQ32_L4_order.png",
  "imgf": "figure/taxa/WSQ32_L5_family.png",
  "imgg": "figure/taxa/WSQ32_L6_genus.png",
  "photo": "figure/photo/WSQ32.jpg"
},
{
  "ID": "WSQ33",
  "description": "樱树林飞人雕像立柱",
  "longitude": 116.313115,
  "latitude": 39.994867,
  "imgp": "figure/taxa/WSQ33_L2_phylum.png",
  "imgc": "figure/taxa/WSQ33_L3_class.png",
  "imgo": "figure/taxa/WSQ33_L4_order.png",
  "imgf": "figure/taxa/WSQ33_L5_family.png",
  "imgg": "figure/taxa/WSQ33_L6_genus.png",
  "photo": "figure/photo/WSQ33.jpg"
},
{
  "ID": "WSQ34",
  "description": "东操场小足球门",
  "longitude": 116.313214,
  "latitude": 39.987912,
  "imgp": "figure/taxa/WSQ34_L2_phylum.png",
  "imgc": "figure/taxa/WSQ34_L3_class.png",
  "imgo": "figure/taxa/WSQ34_L4_order.png",
  "imgf": "figure/taxa/WSQ34_L5_family.png",
  "imgg": "figure/taxa/WSQ34_L6_genus.png",
  "photo": "figure/photo/WSQ34.jpg"
},
{
  "ID": "WSQ42",
  "description": "王克桢楼南门柱子",
  "longitude": 116.314897,
  "latitude": 39.986922,
  "imgp": "figure/taxa/WSQ42_L2_phylum.png",
  "imgc": "figure/taxa/WSQ42_L3_class.png",
  "imgo": "figure/taxa/WSQ42_L4_order.png",
  "imgf": "figure/taxa/WSQ42_L5_family.png",
  "imgg": "figure/taxa/WSQ42_L6_genus.png",
  "photo": "figure/photo/WSQ42.jpg"
},
{
  "ID": "WSQ43",
  "description": "理科5号楼马寅初雕像",
  "longitude": 116.314694,
  "latitude": 39.989891,
  "imgp": "figure/taxa/WSQ43_L2_phylum.png",
  "imgc": "figure/taxa/WSQ43_L3_class.png",
  "imgo": "figure/taxa/WSQ43_L4_order.png",
  "imgf": "figure/taxa/WSQ43_L5_family.png",
  "imgg": "figure/taxa/WSQ43_L6_genus.png",
  "photo": "figure/photo/WSQ43.jpg"
},
{
  "ID": "WSQ44",
  "description": "光华管理学院2号楼西门把手",
  "longitude": 116.313287,
  "latitude": 39.99555,
  "imgp": "figure/taxa/WSQ44_L2_phylum.png",
  "imgc": "figure/taxa/WSQ44_L3_class.png",
  "imgo": "figure/taxa/WSQ44_L4_order.png",
  "imgf": "figure/taxa/WSQ44_L5_family.png",
  "imgg": "figure/taxa/WSQ44_L6_genus.png",
  "photo": "figure/photo/WSQ44.jpg"
},
{
  "ID": "WYXY-1",
  "description": "北京市海淀区·北京大学",
  "longitude": 116.306445,
  "latitude": 39.996181,
  "imgp": "figure/taxa/WYXY-1_L2_phylum.png",
  "imgc": "figure/taxa/WYXY-1_L3_class.png",
  "imgo": "figure/taxa/WYXY-1_L4_order.png",
  "imgf": "figure/taxa/WYXY-1_L5_family.png",
  "imgg": "figure/taxa/WYXY-1_L6_genus.png",
  "photo": "figure/photo/WYXY-1.jpg"
},
{
  "ID": "XW10",
  "description": "30楼秋千",
  "longitude": 116.309363,
  "latitude": 39.988086,
  "imgp": "figure/taxa/XW10_L2_phylum.png",
  "imgc": "figure/taxa/XW10_L3_class.png",
  "imgo": "figure/taxa/XW10_L4_order.png",
  "imgf": "figure/taxa/XW10_L5_family.png",
  "imgg": "figure/taxa/XW10_L6_genus.png",
  "photo": "figure/photo/XW10.jpg"
},
{
  "ID": "XW11",
  "description": "新太阳学生中心一层桌面",
  "longitude": 116.311164,
  "latitude": 39.98888,
  "imgp": "figure/taxa/XW11_L2_phylum.png",
  "imgc": "figure/taxa/XW11_L3_class.png",
  "imgo": "figure/taxa/XW11_L4_order.png",
  "imgf": "figure/taxa/XW11_L5_family.png",
  "imgg": "figure/taxa/XW11_L6_genus.png",
  "photo": "figure/photo/XW11.jpg"
},
{
  "ID": "XW12",
  "description": "百周年纪念讲堂南侧广告牌",
  "longitude": 116.310755,
  "latitude": 39.989626,
  "imgp": "figure/taxa/XW12_L2_phylum.png",
  "imgc": "figure/taxa/XW12_L3_class.png",
  "imgo": "figure/taxa/XW12_L4_order.png",
  "imgf": "figure/taxa/XW12_L5_family.png",
  "imgg": "figure/taxa/XW12_L6_genus.png",
  "photo": "figure/photo/XW12.jpg"
},
{
  "ID": "XW13",
  "description": "图书馆闸机",
  "longitude": 116.309972,
  "latitude": 39.991902,
  "imgp": "figure/taxa/XW13_L2_phylum.png",
  "imgc": "figure/taxa/XW13_L3_class.png",
  "imgo": "figure/taxa/XW13_L4_order.png",
  "imgf": "figure/taxa/XW13_L5_family.png",
  "imgg": "figure/taxa/XW13_L6_genus.png",
  "photo": "figure/photo/XW13.jpg"
},
{
  "ID": "XW14",
  "description": "革命烈士纪念碑",
  "longitude": 116.308191,
  "latitude": 39.992156,
  "imgp": "figure/taxa/XW14_L2_phylum.png",
  "imgc": "figure/taxa/XW14_L3_class.png",
  "imgo": "figure/taxa/XW14_L4_order.png",
  "imgf": "figure/taxa/XW14_L5_family.png",
  "imgg": "figure/taxa/XW14_L6_genus.png",
  "photo": "figure/photo/XW14.jpg"
},
{
  "ID": "XW37",
  "description": "快递服务中心快递柜",
  "longitude": 116.310593,
  "latitude": 39.986624,
  "imgp": "figure/taxa/XW37_L2_phylum.png",
  "imgc": "figure/taxa/XW37_L3_class.png",
  "imgo": "figure/taxa/XW37_L4_order.png",
  "imgf": "figure/taxa/XW37_L5_family.png",
  "imgg": "figure/taxa/XW37_L6_genus.png",
  "photo": "figure/photo/XW37.jpg"
},
{
  "ID": "XW38",
  "description": "正大国际中心西侧正门",
  "longitude": 116.306125,
  "latitude": 39.990605,
  "imgp": "figure/taxa/XW38_L2_phylum.png",
  "imgc": "figure/taxa/XW38_L3_class.png",
  "imgo": "figure/taxa/XW38_L4_order.png",
  "imgf": "figure/taxa/XW38_L5_family.png",
  "imgg": "figure/taxa/XW38_L6_genus.png",
  "photo": "figure/photo/XW38.jpg"
},
{
  "ID": "XW39",
  "description": "燕南园工学院石碑",
  "longitude": 116.308314,
  "latitude": 39.98945,
  "imgp": "figure/taxa/XW39_L2_phylum.png",
  "imgc": "figure/taxa/XW39_L3_class.png",
  "imgo": "figure/taxa/XW39_L4_order.png",
  "imgf": "figure/taxa/XW39_L5_family.png",
  "imgg": "figure/taxa/XW39_L6_genus.png",
  "photo": "figure/photo/XW39.jpg"
},
{
  "ID": "XW40",
  "description": "二体东篮球场西侧物品存放柜柜门",
  "longitude": 116.308631,
  "latitude": 39.990695,
  "imgp": "figure/taxa/XW40_L2_phylum.png",
  "imgc": "figure/taxa/XW40_L3_class.png",
  "imgo": "figure/taxa/XW40_L4_order.png",
  "imgf": "figure/taxa/XW40_L5_family.png",
  "imgg": "figure/taxa/XW40_L6_genus.png",
  "photo": "figure/photo/XW40.jpg"
},
{
  "ID": "XW45",
  "description": "五四体育场西侧塑胶跑道",
  "longitude": 116.312769,
  "latitude": 39.987684,
  "imgp": "figure/taxa/XW45_L2_phylum.png",
  "imgc": "figure/taxa/XW45_L3_class.png",
  "imgo": "figure/taxa/XW45_L4_order.png",
  "imgf": "figure/taxa/XW45_L5_family.png",
  "imgg": "figure/taxa/XW45_L6_genus.png",
  "photo": "figure/photo/XW45.jpg"
},
{
  "ID": "XW46",
  "description": "学一食堂东区大理石桌面",
  "longitude": 116.308133,
  "latitude": 39.987526,
  "imgp": "figure/taxa/XW46_L2_phylum.png",
  "imgc": "figure/taxa/XW46_L3_class.png",
  "imgo": "figure/taxa/XW46_L4_order.png",
  "imgf": "figure/taxa/XW46_L5_family.png",
  "imgg": "figure/taxa/XW46_L6_genus.png",
  "photo": "figure/photo/XW46.jpg"
},
{
  "ID": "XW5",
  "description": "勺园学生宿舍，家@勺园立牌",
  "longitude": 116.30622,
  "latitude": 39.991711,
  "imgp": "figure/taxa/XW5_L2_phylum.png",
  "imgc": "figure/taxa/XW5_L3_class.png",
  "imgo": "figure/taxa/XW5_L4_order.png",
  "imgf": "figure/taxa/XW5_L5_family.png",
  "imgg": "figure/taxa/XW5_L6_genus.png",
  "photo": "figure/photo/XW5.jpg"
},
{
  "ID": "XW6",
  "description": "国际关系学院字碑",
  "longitude": 116.306559,
  "latitude": 39.991417,
  "imgp": "figure/taxa/XW6_L2_phylum.png",
  "imgc": "figure/taxa/XW6_L3_class.png",
  "imgo": "figure/taxa/XW6_L4_order.png",
  "imgf": "figure/taxa/XW6_L5_family.png",
  "imgg": "figure/taxa/XW6_L6_genus.png",
  "photo": "figure/photo/XW6.jpg"
},
{
  "ID": "XW7",
  "description": "佟园食堂门把手",
  "longitude": 116.306746,
  "latitude": 39.990992,
  "imgp": "figure/taxa/XW7_L2_phylum.png",
  "imgc": "figure/taxa/XW7_L3_class.png",
  "imgo": "figure/taxa/XW7_L4_order.png",
  "imgf": "figure/taxa/XW7_L5_family.png",
  "imgg": "figure/taxa/XW7_L6_genus.png",
  "photo": "figure/photo/XW7.jpg"
},
{
  "ID": "XW8",
  "description": "46楼自行车维修点集装箱",
  "longitude": 116.305717,
  "latitude": 39.98878,
  "imgp": "figure/taxa/XW8_L2_phylum.png",
  "imgc": "figure/taxa/XW8_L3_class.png",
  "imgo": "figure/taxa/XW8_L4_order.png",
  "imgf": "figure/taxa/XW8_L5_family.png",
  "imgg": "figure/taxa/XW8_L6_genus.png",
  "photo": "figure/photo/XW8.jpg"
},
{
  "ID": "XW9",
  "description": "家园食堂二层凳子",
  "longitude": 116.308154,
  "latitude": 39.98849,
  "imgp": "figure/taxa/XW9_L2_phylum.png",
  "imgc": "figure/taxa/XW9_L3_class.png",
  "imgo": "figure/taxa/XW9_L4_order.png",
  "imgf": "figure/taxa/XW9_L5_family.png",
  "imgg": "figure/taxa/XW9_L6_genus.png",
  "photo": "figure/photo/XW9.jpg"
},
{
  "ID": "XYY-1",
  "description": "北京市海淀区·北京大学",
  "longitude": 116.313336,
  "latitude": 39.996458,
  "imgp": "figure/taxa/XYY-1_L2_phylum.png",
  "imgc": "figure/taxa/XYY-1_L3_class.png",
  "imgo": "figure/taxa/XYY-1_L4_order.png",
  "imgf": "figure/taxa/XYY-1_L5_family.png",
  "imgg": "figure/taxa/XYY-1_L6_genus.png",
  "photo": "figure/photo/XYY-1.jpg"
},
{
  "ID": "YT-1",
  "description": "北京市海淀区·北京大学体育场",
  "longitude": 116.312115,
  "latitude": 39.994516,
  "imgp": "figure/taxa/YT-1_L2_phylum.png",
  "imgc": "figure/taxa/YT-1_L3_class.png",
  "imgo": "figure/taxa/YT-1_L4_order.png",
  "imgf": "figure/taxa/YT-1_L5_family.png",
  "imgg": "figure/taxa/YT-1_L6_genus.png",
  "photo": "figure/photo/YT-1.jpg"
}
]
